### ISSUE TITLE
Water mirroring meshes on the editor

### ISSUE THREAD

**Issue by 3coms** [Dark-Basic-Software-Limited/GameGuruRepo#1048]
Ignore if is it a bug, but think I should report it and you decide how to label it.
Adding video link to show the issue.

System Specs:
Operating System: Windows 10 Home 64-bit (10.0, Build 19042) (19041.vb_release.191206-1406)
Language: Spanish (Regional Setting: Spanish)
System Model: H97M-D3H
Processor: Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 CPUs), ~3.6GHz
Memory: 16384MB RAM
Windows Dir: C:\WINDOWS
DirectX Version: DirectX 12
Card name: NVIDIA GeForce GTX 1060 6GB
Dedicated Memory: 6052 MB
Current Mode: 1680 x 1050 (32 bit) (60Hz)
Card name: Intel(R) HD Graphics 4600
Dedicated Memory: 112 MB
Current Mode: Unknown

**Comment by 3coms** [comment]
The video link
https://youtu.be/kO8IpXXuAzU

**Comment by plemsoft** [comment]
@3coms Thanks for reporting this issue, could you check if this was fixed in the latest version , also minimize and high gpu use should be fixed, thanks for your help :)
