### ISSUE TITLE
only suppose to blow the bloody doors off. 

### ISSUE THREAD

**Issue by casigus** [Dark-Basic-Software-Limited/GameGuruRepo#1464]
the new update has locked all the doors, like all of them, meaning you have to add a key, connect to the door for every single door, then when the doors unlocked, it won't animate!

![image](https://user-images.githubusercontent.com/68471279/137603111-eca17720-f30f-4006-92f9-21db622a8b97.png)

**Comment by LeeBamberTGC** [comment]
@casigus Doors are handled differently now in MAX, using the new visual logic system so you no longer need to use the IFUSED system.  In the new door script there is a flag you can toggle to lock and unlock the door at the start of the level. By default it will be set to unlocked.  Can you send me (lee@thegamecreators.com) your door model and I will see about getting it working for you (and a good test for me for the new system).

**Comment by LeeBamberTGC** [comment]
@casigus Thanks :)  I think you make a good point about backward compatibility. I will rename the new door script so you can still use the old door script when you legacy assets over. That should help a lot!
