### ISSUE TITLE
3rd Person Mode - Moon Walk

### ISSUE THREAD

**Issue by Teabone3** [Dark-Basic-Software-Limited/GameGuruRepo#168]
In 3rd person mode, if you hold down W and S at the same time (or A and D), the player character will moon walk. This is the case with any character model used.

**Comment by Belidos3D** [comment]
That's awesome, should be a feature :D

**Comment by Teabone3** [comment]
This bug appears to still be there. I'm curious if someone could open up the player LUA script and take a look at what might be the cause?
