### ISSUE TITLE
Painting materials have lost their names again!

### ISSUE THREAD

**Issue by rvanner** [Dark-Basic-Software-Limited/GameGuruRepo#2147]
![image](https://user-images.githubusercontent.com/1503593/154290238-f5770f07-dca3-486b-b4e5-63be08b9cfeb.png)

**Comment by plemsoft** [comment]
@rvanner Yes everything is saved with the level so you might have a old level that had those names , anyway i made a check that you also got the new material names , so you should not see it again. ready from the next build :)
