### ISSUE TITLE
Terrain Flattening - Doesn't adjust for some rotations

### ISSUE THREAD

**Issue by dllllllllllb** [Dark-Basic-Software-Limited/GameGuruRepo#2190]
Terrain flattening underneath an object doesn't adjust for some rotations angles
https://gyazo.com/3599b501cdbe7dcb2cad5d02a40a12cc

**Comment by ThomasJowett** [comment]
https://gamedev.stackexchange.com/questions/165505/why-rotating-an-object-only-on-its-local-x-axis-result-in-sudden-180-degrees-cha

This seems like the same issue, when pressing "R" to rotate an object it rotates it using a quaternion, meaning that an orientation of x= 180 y = 45 z = 180 is the same as x = 0 y = 135 z = 0 and can produce either based on the previous rotation, the calculation of the flat area only uses the y rotation and so sometimes uses the wrong angle.

**Comment by LeeBamberTGC** [comment]
@ThomasJowett Yes that is the phenomena right enough.  Maybe the solution is to ignore the euler and instead obtain the quat from the object itself, that way the flattened area always has the true rotation.

**Comment by LeeBamberTGC** [comment]
Confirmed fixed in latest build.
