### ISSUE TITLE
Terrain Flattening - Adding behaviours have a huge performance hit

### ISSUE THREAD

**Issue by dllllllllllb** [Dark-Basic-Software-Limited/GameGuruRepo#2191]
Adding a behaviour to an object that has terrain flattened underneath drastically drops the fps. Tested it with collection count, door and rotation behaviours, all with the same effect.
https://www.youtube.com/watch?v=6b2YiJFp520

**Comment by LeeBamberTGC** [comment]
@dllllllllllb See if you can reproduce this one, and trace the bottleneck if there is one.

**Comment by dllllllllllb** [comment]
@LeeBamberTGC When you add any movement behaviour to objects with terrain flattening, it will flatten the terrain under the object every update. It should be disabled when not in the editor.

https://www.youtube.com/watch?v=bkM0cY6yKsA
