### ISSUE TITLE
Standalone game. Changes to graphics settings change the position of trees. Bug.

### ISSUE THREAD

**Issue by janekste** [Dark-Basic-Software-Limited/GameGuruRepo#2933]
Three screenshots from the same position with different graphics settings. All three screenshots have different trees (different number), but there should be the same trees. I just changed the graphics settings. Please fix the bug.

There is only an automatically generated forest here . I didn't set anything manually.

Thank you for your time.

![image](https://user-images.githubusercontent.com/55485525/164762619-81090f99-4eaa-432c-a0dc-46f045e511a9.png)
![image](https://user-images.githubusercontent.com/55485525/164762642-84d5d59a-57e2-4ff5-8cda-b3f9ece8bf3f.png)
![image](https://user-images.githubusercontent.com/55485525/164762659-7ce9e90c-64f5-4a29-9fbc-b654e85a32fc.png)

**Comment by PaulSJ** [comment]
The tree quality will change, which may cause some trees to become billboards sooner, but the trees shouldn't move. 

Unfortunately I can't replicate this with the current version, can you give me some steps to reproduce it? If it is an old level then it may suffer from a change in the save file format that we made a while back, so new levels wouldn't have this problem.

**Comment by janekste** [comment]
@PaulSJ 

https://youtu.be/PkifSOQqIBQ

I recorded a video for you. I have generated a new level in the canyon. Just get close to the trees and change the graphics settings several times. On different graphics settings, you will see a different number of trees, trees in different places. I see this problem both in the level editor and in the standalone game. Some trees become invisible, and others are visible, depending on the change of graphics. Just watch the video to the end.

**Comment by PaulSJ** [comment]
I think I see what's happening. When the graphics settings change, the terrain becomes slightly less detailed, which changes the angle of some of the slopes. Trees are automatically removed on slopes that are too steep, so the slope angle might be very close to this critical value and then the settings change it just enough to flip it between the two.

If you manually place or move a tree then it will become locked as visible since then the system knows that you definitely want the tree there.

**Comment by janekste** [comment]
@PaulSJ 
This text was typed using Yandex online translator.

Thanks for the explanation. Now I understand what's going on. Now I know that I have to plant each tree manually so that it is always in its place. I should pay special attention to all the trees near the slopes. Now everything is clear.

But I think it shouldn't be like that. If the trees are automatically generated, then all the trees should fix their position and the position should not change. Trees should not appear or disappear due to changes in terrain detail. Just imagine the situation. The player is playing a game, walking in the forest. During the game, it changes the graphics settings and for this reason, new trees grow around the player's position, or some disappear. I do not know how you perceive it, but I perceive it as a bug.

Thank you for your time.

**Comment by PaulSJ** [comment]
I've added a button called Lock Tree Visibility that will prevent terrain changes from affecting tree visibility. However due to the way it works the only way to undo it is to randomize all the trees again, so it should only be done when you are happy with the terrain.

**Comment by janekste** [comment]
@PaulSJ 
Thank you for your work. I confirm. The problem is solved. I'm happy.
