### ISSUE TITLE
Game Guru Tagline

### ISSUE THREAD

**Issue by Teabone3** [Dark-Basic-Software-Limited/GameGuruRepo#304]
With the new branding of Game Guru's tagline of which says "Game Making For Everyone" it still displays "The Easy Game Maker" on the player controls splash screen during test game.

An incredibly minor thing i noticed last night. But it was pointed out to me by my colleagues who were lesser impressed by a presentation i gave with GG that displays that at the top left hand corner.

This issue post is a duplicate of #265 (my bad)

**Comment by HierToo** [comment]
#265 Is this the same?

**Comment by Teabone3** [comment]
yep! Thanks @HierToo , didn't notice that post
