### ISSUE TITLE
This kind of scene will be doable in GGMax?

### ISSUE THREAD

**Issue by 3coms** [Dark-Basic-Software-Limited/GameGuruRepo#3218]
Hi
**Note: I already know about particles, in fact, I own the AGK particle editor.**

I decided to model a emitter and some grains of sand, because:
1- Not everything is going to be feasible with AGK editor.
2- Particles are not LUA supported yet, as a mesh can be.

This is just an experiment since I'm really looking for a decent waterfall.
**Assimp opens the mesh, while GGMax closes to the desktop when I try to import it.**
The whole scene is 1 emitter (a tube) and the grains of sand (4k)

I'm afraid here the "Just 100 materials" prompt will come, although, **they are 4k meshes sharing 1 material nor 4k materials**
But I think this time is not just the 100+ materials, but the 4k meshes.
I like to break stuff, that usually generates a lot of chunks (debris), should I forget about breaking stuff in GGMax?

The emitter plus the animated grains of sand in 3ds Max 2015

https://youtu.be/n6afTusj2gs

**Comment by MonkeyFrogStudio** [comment]
It's better to "fake" something like this in a a game engine then to attempt to simulate this via physics and the like. Make one "mesh" made of several polygonal meshes (even if they are separate quads) and animate them falling out of the tube. Do your physics in 3DS max, but save it out as a single animation via FBX and use that in MAX. Then you get one model, one material, etc. And it's light-weight and works in MAX.

**Comment by 3coms** [comment]
`Do your physics in 3DS max, but save it out as a single animation via FBX and use that in MAX. `
This is what I'm doing since GG times when modeling the explodable barrels, boxes, etc
Anyway, there is a difference this time, and it is the chunks qty, never before have I attempted to run an animated mesh with that quantity of chunks (debris, pieces, wherever you want), so, I raise my question, do you know how many meshes can have a multi-object in GGMax? (if any)
If you never try you never know. :)

**Comment by MonkeyFrogStudio** [comment]
Sigh ...

**Comment by jbthenext** [comment]
The issues board is for bug reports or feature requests this is neither, this would be better suited to a discussion in the discord or forums

**Comment by 3coms** [comment]
Sorry, but:
**Assimp opens the mesh, while GGMax closes to the desktop when I try to import it.**
it is a bug, at least for me, the rest is only to try to explain what happens to it.
