### ISSUE TITLE
Sliding Door bug

### ISSUE THREAD

**Issue by Maro32** [Dark-Basic-Software-Limited/GameGuruRepo#3267]
Hello!

I found a strange thing about the sliding door. It works in proportion to the distance. When you are close to the door it works as intended. If the door is far away it won't do anything until you get closer, and if you do, it will start to open and close until you get close enough.
I attached a file where you can see this in action.

[Door Bug.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8844632/Door.Bug.zip)

**Comment by AmenMoses** [comment]
[door_sliding.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8846408/door_sliding.zip)

There you go.

**Comment by AmenMoses** [comment]
[door_sliding.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8846447/door_sliding.zip)

Try this one.

**Comment by AmenMoses** [comment]
[door_sliding.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8846497/door_sliding.zip)

Try this one instead.

**Comment by Maro32** [comment]
> [door_sliding.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8846497/door_sliding.zip)
> 
> Try this one instead.

Thanks a lot! It works pretty well. Only 2 things that I can say as a con to this LUA.
The first is that the distant door still doesn't open until you get closer, but it's fine for me.
The second is a bit strange. If you set the 'Door Delay' and the 'Period' to a really small number, the door jumps back to closed position. It depends on the 'Distance' property aswell, but not too much. For example with Distance: 100 and Door Delay: 0, if you set the Perion to 50, it closes, but with Period: 51, it works fine. If the Distance is still 100, but you set the Door Delay to 10, you need to set the Period to only 33 to the door remains open. Distance: 100, Door Delay: 20, the lowest Period you need is 13. With Distance 100 and the Period is set to 0, you need at least 33 to the Door Delay. But with 200 Distance and 0 Period, the Door Delay is need to be at least 50. The further the door opens, you need a bit bigger minimum numbers to work as intended. By the way it's more like interesting, than a noticable difference, so I can live with that, just mentioned that.
And the pros are far beyond the cons. The strange open and close behavior of the door is gone, and the Door Delay works again. Thanks again for this LUA, I appreciate it!

**Comment by Necrym59** [comment]
You have the distance to the door too far away - set them to always on should fix it

**Comment by Maro32** [comment]
> You have the door too far away - set them to always on should fix it.

Ohh I see! Yeah, that's solved the problem, thanks!

**Comment by LeeBamberTGC** [comment]
@Maro32 @Necrym59 Are we happy to replace the door sliding behavaior with AmenMoses latest one for this Friday?

**Comment by AmenMoses** [comment]
The period value is milliseconds to open so setting it less than 100 or so is a bit daft as it will move way too fast.

Sort of highlights a limitation in Dynamic Lua though as sometimes you want to specify a minimum value for a parameter whilst having no maximum, in this case you would want period to not be allowed below say 100 ms as that would cause strange behaviour at low FPS (i.e. at 10 FPS that would be an instantaneous door opening and the math could go a bit strange).

**Comment by Maro32** [comment]
> @Maro32 @Necrym59 Are we happy to replace the door sliding behavaior with AmenMoses latest one for this Friday?

Absolutely! This script also solved the issue #3210. Only one more thing that I can imagine in this script, is if you can separate the open and close delays in the auto mode. It's useful for doors that you can open without delay, and you need to be fast to get through before it closes, like in the good old Tomb Raider games. :) But I know not to be insatiable, this script is already great. :)

**Comment by AmenMoses** [comment]
[door_sliding.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8856453/door_sliding.zip)

Like that you mean?

**Comment by AmenMoses** [comment]
Btw, the original intention of the period and delay parameters was to allow the user to tweak the door motion to match a sound sample that's why they were in milliseconds.

With the script I just attached you have a new door mode 'DelayedClose' and a CLOSE_DELAY parameter which is in seconds.

**Comment by AmenMoses** [comment]
[door_sliding.zip](https://github.com/TheGameCreators/GameGuruRepo/files/8856509/door_sliding.zip)

Included a validity check on new parameter for backwards compatibility.

**Comment by Necrym59** [comment]
As usual Amens work is excellent update as soon as you can Lee

**Comment by AmenMoses** [comment]
The new auto close behaviour only works when the door is activated by a switch or similar btw.  
So you would activate the door at a distance then after the delay time will automatically close again.

**Comment by Maro32** [comment]
@AmenMoses WOW! You nailed it in no time! Amazing job! Thanks a lot again!
@LeeBamberTGC Please put the last script from AmenMoses in the friday update. It works like a charm!

**Comment by LeeBamberTGC** [comment]
@Maro32 Will do!  @AmenMoses Many thanks!!

**Comment by Maro32** [comment]
@LeeBamberTGC @AmenMoses thank you very much guys!

**Comment by Maro32** [comment]
@AmenMoses do you mind if I summon you one more time in issue #3315 ?

**Comment by Maro32** [comment]
@LeeBamberTGC I found an issue with the current version of this LUA. If you use multiple doors with multiple switches, it doesn't work as intended. AmenMoses made an update for this LUA that works perfectly in this case as well, it's in #3315 . Could you include it in the next update please? Thank you!

**Comment by LeeBamberTGC** [comment]
@Maro32 FIxed the issue 3315 for next build :)
