### ISSUE TITLE
GGMAX - Enhancement Request - (Interlevel Teleport)

### ISSUE THREAD

**Issue by Necrym59** [Dark-Basic-Software-Limited/GameGuruRepo#3334]
Can we implement a Spawn Marker (an alternate map start point) from level teleports as an option.

There are many instances this can be used such as finding a code/keycard object that then allows for inter-level teleport. These are similar to winzones but are not winzones. I have already a teleport script ready that allows for level loading but it currently always appears at the Start Marker. 

If we have a Gobal flag that is checked when a map loads so it knows its a level teleport then it would start at a designated Spawn Marker instead of the normal Start Marker. 
![spawnmarker](https://user-images.githubusercontent.com/95015657/174875117-3dc0ce8b-4a2e-4f67-b336-67b52385afdb.png)
example: Global Flag: TeleportLoad(3) would load level map and spawn at Spawn Marker(3).

This allows for multiple map changing back and forth such as one main map that branches off to cave maps, dimension maps or base maps for example then back to the main map to finish at a winzone.

This scenario is perfect for all style of games especially RPG style where multiple zone maps could be used.
![Interlevel](https://user-images.githubusercontent.com/95015657/174875225-c4ed43f3-1b9b-4321-82f4-8857f33fd269.png)

**Comment by Ratall** [comment]
A truly excellent idea and well presented. I do hope they listen to you and implement this.
