### ISSUE TITLE
GG Max- EXP Build - RPG Template ?

### ISSUE THREAD

**Issue by Tum1370** [Dark-Basic-Software-Limited/GameGuruRepo#4344]
Why does the little video on the RPG Template in the demo games, show a different level to the level that is connected to the project.
In the video you can see the player running up to a trader next to a shop of some kind, Yet the level attached to this is an old first test one that doesnt even work properly ?

EDIT : Just so you know, I DO have the Aztec Kit DLC and its installed.

I have uninstalled and reinstalled Max several times and that still has not changed this.

![1](https://user-images.githubusercontent.com/66874403/228596870-055b73f6-6a20-454b-a44a-be6f928559f5.png)
![2](https://user-images.githubusercontent.com/66874403/228596887-5633d426-81b0-4f81-8b65-24b8a45e037f.png)

**Comment by thor49** [comment]
Tum..
I had exactly the same problem with the RPG Template level..
I also have the Aztec Kit DLC..
It had me puzzled... then I thought... wait a minute did I not
copy this to my Writable area so I could play and change it..

Yes thats what it was the new version was in the steam-instal-drive..
And my old version (in my writeable area drive) was being picked up and run by Max.
So I copied the new version to my writable area and bingo got the new version working.

Thought I would pass this on just in case you had done the same..

**Comment by Tum1370** [comment]
@thor49 @LeeBamberTGC Thanks Thor, That was the exact problem. After deleting the RPG Template from the mapbank in mydocuments folder, it then downloaded the newer version.

This is exactly the point why, these demos, should not be downloading in to our own mydocuments folder, and been in with all our own maps. Its making our own map storage area very messy.

Please do something about this, rather than having every demo map copying over in to the mydocuments folder.
Just add some kind of option, before loading in to the demo storyboard, asking whether you just want to play the demo, or copy the demo to your mydocuments mapbank, so you can edit it ??

**Comment by Tum1370** [comment]
Am closing this issue as it is resolved for me, But really this copying of demo games to our mydocuments mapbank needs sorting.
It gets very messy, and look at what happened here. The latest version of the new demo didnt even copy to it as the old one was still there.
