### ISSUE TITLE
Max shooting experience suggestion

### ISSUE THREAD

**Issue by Peri32** [Dark-Basic-Software-Limited/GameGuruRepo#4485]
I can see in lot of modern shooter, when enemies hit you the camera shake a little bit, I think its can be a big improvement to the experience if its possible to add it as a option.

**Comment by MonkeyFrogStudio** [comment]
Please do a search before reporting a bug or offering a suggestion. Camera shake has been requested a few times:

https://github.com/TheGameCreators/GameGuruRepo/issues/3468

https://github.com/TheGameCreators/GameGuruRepo/issues/1953

Part of point 5 in this thread:
https://github.com/TheGameCreators/GameGuruRepo/issues/498

**Comment by Peri32** [comment]
No problem, thanks

בתאריך יום ג׳, 18 באפר׳ 2023, 7:29, מאת MonkeyFrogStudio ‏<
***@***.***>:
