### ISSUE TITLE
GG Max - EXP - BUG - AI Character Attack - ALERT Tickbox ?

### ISSUE THREAD

**Issue by Tum1370** [Dark-Basic-Software-Limited/GameGuruRepo#4497]
Does the ALERT tickbox actually work with Character Attack ?
I have tested this a lot, and whether i have this box ticked or not, The character starts attacking you at the same time.
I had 2 characters side by side, one had the box ticked, the other did not.
Both start attacking you at same time.
![Untitled](https://user-images.githubusercontent.com/66874403/233037234-de7a8666-3f9a-4f09-ba13-351c5f1c20b7.png)

**Comment by davetgc** [comment]
I'll let the dev team answer this, and mark as a bug if appropriate.

**Comment by LeeBamberTGC** [comment]
@Tum1370 It only pushes the character initally into an instant ALERT posture when the level starts, it does not last long but might be needed if you start a new level amogst enemies and want to skip discovery:

Alert On at start:
![image](https://user-images.githubusercontent.com/35840583/233380335-39cd12ed-1fe3-4206-a6bb-632dd8630783.png)

Alert Off at start:
![image](https://user-images.githubusercontent.com/35840583/233380501-62d98e54-b65f-4da3-b2b0-49fa269a621f.png)

I have moved this to a feature request in case there was something specific you expected and did not see with this idea.

**Comment by Tum1370** [comment]
@LeeBamberTGC I thought this instant alert meant the AI started attacking quicker ? but with the test i sent, they both attack at the same time whether it was ticked or not ? Thats why it didnt look like it did anything ?

**Comment by LeeBamberTGC** [comment]
@Tum1370 Yes, it makes more sense if you know how to read the behaviour editor logic for the character attack. Right now, that's just me :)
