### ISSUE TITLE
These files are encrypted and cannot be loaded into Gameguru editor. 

### ISSUE THREAD

**Issue by spellborne** [Dark-Basic-Software-Limited/GameGuruRepo#5397]
Getting following error when starting GMAX Gameguru:

These files are encrypted and cannot be loaded into Gameguru editor.
several of the above then:
Runtime error: 501 Image Number 63201 ()
Then crashes.

![Screenshot (3)](https://github.com/TheGameCreators/GameGuruRepo/assets/88847676/c8b829c0-a3a9-43f4-8541-71c329128ffb)
![Screenshot (4)](https://github.com/TheGameCreators/GameGuruRepo/assets/88847676/9728717e-706c-4b74-b2f0-250a852c9463)

With support and being looked into

**Comment by LeeBamberTGC** [comment]
@spellborne Added this to the next EXP build. Will upload in 10-20 minutes:

sprintf ( pMessage, "The file (%s) is encrypted and cannot be loaded into GameGuru editor", checkForEncryptName);
MessageBox(NULL, pMessage, "GAME GURU Error", MB_ICONEXCLAMATION);

**Comment by LeeBamberTGC** [comment]
@spellborne Can you run the latest EXP build and send a new screenshot showing the improved debug info, thanks!

**Comment by LeeBamberTGC** [comment]
@spellborne yes go to the BETA tab and then use the password "lettesterin456" to reveal the special EXPERIMENTAL branch :)

**Comment by spellborne** [comment]
Hi Lee,

Ran EXP version, same errors, with crash, not sure if you have seperate location for your error log.

Windows errors also attached.

Cheers

Dave

 
 

Sent: Wednesday, April 03, 2024 at 9:54 PM

**Comment by synchromesh62** [comment]
Isnt this what is supposed to happen if you try to import encrypted files from a standalone ?
or am i missing something ?

**Comment by spellborne** [comment]
It’s a new install, following an uninstall and clearing the install directory. Sent using the mobile mail appOn 04/04/2024 at 19:41, synchromesh62 wrote:
                
            
            
                
                    From: "synchromesh62" ***@***.***>Date: 4 April 2024To: "TheGameCreators/GameGuruRepo" ***@***.***>Cc: "Mention" ***@***.***>,"spellborne" ***@***.***>Subject: Re: [TheGameCreators/GameGuruRepo] These files are encrypted and cannot be loaded into Gameguru editor.  (Issue #5397)
                
                
Isnt this what is supposed to happen if you try to import encrypted files from a standalone ?
or am i missing something ?
