### ISSUE TITLE
GGMAX Bug - Artifacts appearing on distant mountains 

### ISSUE THREAD

**Issue by korodai** [Dark-Basic-Software-Limited/GameGuruRepo#5695]
Glitched artifacts appearing on distant mountains when looking around.

    CPU Brand: Intel(R) Core(TM) i7-9700KF CPU @ 3.60GHz
    Speed: 3600 MHz
    Cores: 8 logical processors, 8 physical processors

    OS: Windows 10 (64 bit)

    GPU: NVIDIA GeForce RTX 3070
    Driver Version: 32.0.15.6070 (Date: 7/10/2024)
    Primary Display Resolution: 1920 x 1080
    VRAM: 8191 MB

    RAM: 32 GB (32687 MB)

    Total Available Space: 1,906,244 MB (~1.9 TB)

![20240828074206_1](https://github.com/user-attachments/assets/d11d0577-1078-498e-9e22-0f4fcf18ebdf)

**Comment by korodai** [comment]
![20240828074158_1](https://github.com/user-attachments/assets/3f8c8d76-46cd-409e-a567-5779094df955)

**Comment by Necrym59** [comment]
Confirmed

**Comment by extremestrategy** [comment]
Having this problem as well, currently I'm on EXP build and this only seems to effect one of my maps as of now.  I made the map earlier today.

![image](https://github.com/user-attachments/assets/fb05dd64-d3c6-4957-9220-a08c450f0c76)

**Comment by extremestrategy** [comment]
I'm not getting it now, but it was consistent, the latest updates may have fixed it.
